In [1]:
import numpy as np 
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [2]:
df=pd.read_csv('houseprice.csv')
df

area  room  age  price
0  2000   4.0   15  30000
1  2400   3.0   20  38000
2  2800   NaN   30  45000
3  3200   3.0   40  50000
4  4000   5.0   50  55000

In [3]:
import math
roomdata=math.floor(df.room.median())
roomdata

3

In [4]:
df.room=df.room.fillna(roomdata)
df

area  room  age  price
0  2000   4.0   15  30000
1  2400   3.0   20  38000
2  2800   3.0   30  45000
3  3200   3.0   40  50000
4  4000   5.0   50  55000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','room','age']],df.price)

LinearRegression()

In [6]:
reg.predict([[2400,4,10]])

array([34000.])

In [7]:
reg.predict([[2500,3,20]])

array([39500.])

In [37]:
df=pd.read_csv('hiring.csv')
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5     three          7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [38]:
import math
df_test=math.floor(df.test_score.mean())
df_test

7

In [39]:
df.test_score=df.test_score.fillna(df_test)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5     three          7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [40]:
df.experience=df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5     three          7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [41]:
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [42]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [43]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [44]:
reg.predict([[12,10,10]])

array([93747.79628651])