In [8]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [9]:
df=pd.read_csv('homeprice.csv')
df

area    price
0  1000   555000
1  1200   562000
2  1600   600000
3  2000   800000
4  2400  1000000

In [10]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [12]:
model.predict([[1400]])

array([626292.68292683])

In [13]:
import pickle

In [14]:
with open('modelpickel','wb') as f:
    pickle.dump(model,f)

In [25]:
with open('modelpickel','rb') as f:
    mp=pickle.load(f)

In [26]:
mp.predict([[1400]])

array([626292.68292683])

In [22]:
import joblib

In [23]:
joblib.dump(model,'modeljoblib')

['modeljoblib']

In [27]:
mj=joblib.load('modeljoblib')


In [28]:
mj.predict([[1400]])

array([626292.68292683])